### ISSUE TITLE
Vizalert - OSError: Unable to cleanup temp directory .\temp\, error

### ISSUE THREAD

**Issue by praneeth1987** [tableau/VizAlerts#160]
We are using Vizalert 2.1.0 and we keep on getting "OSError: Unable to clean up temp directory .\temp\, error: [Error 2] The system cannot find the file specified:". Because the file already deleted by configuration file settings. in the configuration file, we made 25 hours for temp file retention. but Vizalert trying to delete the fail from the program after 25 hours. even we modified the retention to 7 days. but the program looking for a week ago file. Can you please advise how to eliminate the warning message?

**Comment by mcoles** [comment]
Hello, I'm not sure I understand why VizAlerts is having difficulty cleaning up the temp directory. That message indicates it can't find the files it's supposed to be deleting. Here are three questions that will help narrow down the issue:

1. Are you executing VizAlerts with the working directory context set to your VizAlerts installation path?
2. Does VizAlerts have full read/write/delete access to the temp folder?
3. Does VizAlerts run normally, and create files in the temp folder, prior to this error being thrown?

**Comment by praneeth1987** [comment]
We are getting below alert notifications mails frequently when Vizalerts are getting executed.

OSError: Unable to cleanup temp directory .\temp\, error: [Error 2] The system cannot find the file specified: u'.\\temp\\20200623033104599000_MainThread_VizAlertsConfig-ScheduledTriggerViews.csv'

We are using the default working directory and we are executing it with admin user.

The below is the snapshot of the config file we are using 

# Local paths settings
log.dir: ".\\logs\\"                            # folder write dump log files to. Will be created if it does not exist.
log.dir.file_retention_seconds: 432000          # retain log files for default of 5 days
log.level: DEBUG                                # level of log verbosity
schedule.state.dir: ".\\ops\\"                  # file written to keep the last run state for schedules
temp.dir: ".\\temp\\"                           # folder to write temporary files to (csv, png for viz exports). Will be created if it does not exist.
temp.dir.file_retention_seconds: 86400          # retain temp files for default of 25 hours, mostly for debugging


As per retention seconds, it is checking for previous days file and as it is not available it is throwing alerts.
Even now vizalerts is working fine, but frequently getting this alert notifications

**Comment by mcoles** [comment]
So, the cleanup code runs at the very end of the VizAlerts cycle, and the code lists all files in the temp folder, determines which are too old, then tries to delete them. If a file is being held open by something like Excel, this step will fail (though with a different error). If this is happening intermittently, then my best guess is that some other process is deleting files between when VizAlerts goes to list them, and actually trying to delete them. Is is possible you have another instance of VizAlerts running that uses the same folders? Or, are there any other processes that might be messing with files in those folders?

Another way to try and troubleshoot this would be to move your VizAlerts installation to a new folder structure, so that anything interfering with the originals will no longer conflict with it.

**Comment by praneeth1987** [comment]
As of now no other processes are messing up with these files as we have only Tableau and VizAlerts installed in that machine.

Yes, moving the VizAlerts to another folder might help.

**Comment by praneeth1987** [comment]
Also one more thing, we are keeping the rentention status as 24 hrs and it is looking for that files, Even we have increased the period but still it is looking for the out of period files and throwing error as file missing which is very strange
