### ISSUE TITLE
How to send csv file via VizAlerts

### ISSUE THREAD

**Issue by TNS-reaj** [tableau/VizAlerts#162]
Hello,
I have successfully installed VizAlerts on our DEV system. I have tested "Test 29: Consolidate email w/multiple attachments" successfully which there are three file formats png, CSV, and pdf that attached in the email. But when I subscribe to the view, there is no CSV in the format. When I subscribe to the image format, there is no CSV file attached to the email. 
Please advise.
Thanks
Jennifer

**Comment by mcoles** [comment]
You need to subscribe to the view on one of the custom schedules you created in [this step](https://github.com/tableau/VizAlerts/blob/master/docs/install_guide.md#custom-subscription-schedules) of the install process.

**Comment by TNS-reaj** [comment]
Hi Matt,

[image: image.png]
I try to create a calculated field as "Email Attachment" the content
VIZ_CSV(), but it shows an unknown function. Anything wrong?
Thanks

**Comment by mcoles** [comment]
'VIZ_CSV' in single or double quotes.

**Comment by TNS-reaj** [comment]
I have added an "Email attachment" under the Email Action Setting. And
republished it. On the server side, I ran the vizalerts.exe without error.
But still, no CSV file attached to the email.

[image: image.png]

**Comment by mcoles** [comment]
Could you please show me images of:

1. The calculation for "Email Attachment" and that it is in the viz somewhere (rows, columns, or Details shelf)
2. The test_alert comment you are entering to kick off the alert (or the subscription that you created for it)
3. The email you receive

Having all three will make this process much quicker to troubleshoot. Thanks!

**Comment by TNS-reaj** [comment]
Hi Matt,
Here are the screenshots. Please let me know if you need more information.
Thank you for your help.

**Comment by mcoles** [comment]
Hi Jen, I do not see them, so I think that GitHub might not allow you to post them by replying to the email. Can you please try adding a response directly in GitHub instead, rather than replying via email?

**Comment by TNS-reaj** [comment]
<img width="723" alt="01" src="https://user-images.githubusercontent.com/65303850/87682120-77878200-c74d-11ea-9461-947ec0fd4152.PNG">
<img width="339" alt="02" src="https://user-images.githubusercontent.com/65303850/87682143-7f472680-c74d-11ea-9a9f-d1cdc1f789c5.PNG">
<img width="587" alt="03_top" src="https://user-images.githubusercontent.com/65303850/87682163-840bda80-c74d-11ea-9c03-3a88707573c9.PNG">
<img width="537" alt="03_bottom" src="https://user-images.githubusercontent.com/65303850/87682173-866e3480-c74d-11ea-8474-a674cc54d6f6.PNG">

**Comment by TNS-reaj** [comment]
<img width="537" alt="03_bottom" src="https://user-images.githubusercontent.com/65303850/87682205-9423ba00-c74d-11ea-92b7-be99f63012b1.PNG">

**Comment by TNS-reaj** [comment]
![01](https://user-images.githubusercontent.com/65303850/87682625-0e543e80-c74e-11ea-8773-5f89eafa04c0.JPG)
<img width="339" alt="02" src="https://user-images.githubusercontent.com/65303850/87682632-10b69880-c74e-11ea-8469-116de894b6ac.PNG">
<img width="587" alt="03_top" src="https://user-images.githubusercontent.com/65303850/87682638-12805c00-c74e-11ea-9628-6c01babef151.PNG">
<img width="537" alt="03_bottom" src="https://user-images.githubusercontent.com/65303850/87682650-144a1f80-c74e-11ea-979f-01a2ffb82540.PNG">

**Comment by mcoles** [comment]
Okay, great, thanks! One thing that I could not verify was that you had added the Email Attachment calculation to the viz scope (either on Rows, Columns, or the Detail shelf). Can you confirm you did that?

If you have, then the second thing that could have happened is that the schedule was not ready to run yet when you ran VizAlerts.exe. The way it works is to collect info for what subscriptions are out there, on what schedules, and record the time they should next run. If the _next_ run of VizAlerts.exe detects that the current time has passed, it runs the alert. But you must have one execution before, and then after the schedule was scheduled to next run at for this to work. An easier way is to add the comment "test_alert" to the viz, then run VizAlerts.exe one time. This will run the alert immediately, once. This feature was built in so that you can test your alerts without having to wait for the next pass of your schedule.

**Comment by mcoles** [comment]
By "comment", I mean an actual comment in Tableau Server, like so:

https://github.com/tableau/VizAlerts/blob/master/docs/media/image23-ug.png

**Comment by TNS-reaj** [comment]
Hi Matt,
What is mean "added the Email Attachment calculation to the viz scope"? I have added Email Attachment on the workbook that I subscribed to and added Email Attachment on VizAlertsConfig. The vizalerts.exe was scheduled on the server and it is running every minute. I have added "test_alert" in the comment. But the email report still without csv file.

**Comment by mcoles** [comment]
You should not add anything to VizAlertsConfig. That only tells VizAlerts what alerts to run, and when. The definition of the alerts themselves are always in the trigger views you build--in your case, Alumni Email,

In Alumni Email, drag the Email Attachment to the Detail shelf as I show here. That will put the data in the actual viz, rather than just being a field that you defined. When it is a part of the viz detail, VizAlerts will have access to it and use it appropriately.

![image](https://user-images.githubusercontent.com/14928335/87693633-11493200-c742-11ea-9215-66b221206f2f.png)

**Comment by TNS-reaj** [comment]
<img width="268" alt="05" src="https://user-images.githubusercontent.com/65303850/87704522-86c8f880-c76a-11ea-8e2f-cae1077d6225.PNG">

I have cleaned up VizAlertsConfig and re-published it. 
I dragged Email Attachment to the detail shelf and republished it. The email still didn't attach csv file. Don't know where is wrong.

**Comment by TNS-reaj** [comment]
<img width="268" alt="05" src="https://user-images.githubusercontent.com/65303850/87705004-3bfbb080-c76b-11ea-8f77-7386f0847483.PNG">

I have cleaned up VizAlertsConfig and re-published it.
I dragged Email Attachment to the detail shelf and republished my view (Alumni Email). The email still didn't attach csv file. Don't know where is wrong.

**Comment by mcoles** [comment]
In the folder you are running the EXE from, there should be a temp folder. In the temp folder, can you look at the CSV that was generated from your AlumniEmail viz, open it, and confirm that the Email Attachment field is listed in it, with the value "VIZ_CSV()" ?

**Comment by TNS-reaj** [comment]
The CSV file has generated in the temp folder but it is empty.

**Comment by mcoles** [comment]
Okay, that doesn't really make much sense, since if it was empty, VizAlerts would not have emailed you at all.

Let's do a series of images once again, one for each bullet point:

1. Show the viz (redacted if needed) for Alumni Email, just like you'd see when you access it on Tableau Server.
2. Add a brand-new test_alert comment, and show the screenshot
3. Show the CSV file generated in the temp folder for AlumniEmail, and open in a text editor to show the contents too (redact if needed)
4. Show the email result, if any was received.

**Comment by TNS-reaj** [comment]
1. I have deleted my workbook and republished the original workbook and scheduled email report.
2. Added the 'test_alert' to the comment. see the screenshot. Then scheduled the email report.
3. Add "Email Attachment" to my workbook and republished it then scheduled the email report.

All these three tests are no CSV file generated in the temp folder and all email reports are the same without csv file. 


<img width="256" alt="06" src="https://user-images.githubusercontent.com/65303850/87717380-47a4a280-c77e-11ea-9409-ba167d2ef173.PNG">

**Comment by TNS-reaj** [comment]
<img width="575" alt="07" src="https://user-images.githubusercontent.com/65303850/87719574-8ee06280-c781-11ea-81ff-862e83dda202.PNG">
<img width="131" alt="08" src="https://user-images.githubusercontent.com/65303850/87719581-90aa2600-c781-11ea-9f01-8c7afb3eb4aa.PNG">

**Comment by TNS-reaj** [comment]
In these two days, sometimes the temp files are generated sometimes are not but all generated temp files are empty.

**Comment by mcoles** [comment]
Alright, I need to see the log output from an execution where you used the test_alert comment. Could you paste that in, please? (again, redacting any sensitive server names). Something is wrong because these things just don't add up. Feels like some install steps may have been missed, perhaps. For example, if your schedule was left enabled, it would explain the email behavior. But the test_alert comment would work around that, so it's unclear why that part isn't working. Logs will likely help clarify...i hope.

**Comment by TNS-reaj** [comment]
[VizAlerts.log](https://github.com/tableau/VizAlerts/files/4934194/VizAlerts.log)

**Comment by TNS-reaj** [comment]
I tried to disable the schedule, then the email will not send out. I have to enable the schedule, then the email can send out.

**Comment by mcoles** [comment]
Line 18: MainThread - 2020-07-16 11:18:05 - [INFO] - main - Processing a total of 0 alerts
	Line 36: MainThread - 2020-07-16 11:33:04 - [INFO] - main - Processing a total of 0 alerts
	Line 54: MainThread - 2020-07-16 13:15:42 - [INFO] - main - Processing a total of 0 alerts
	Line 72: MainThread - 2020-07-16 17:10:45 - [INFO] - main - Processing a total of 0 alerts

This is pretty key. VizAlerts isn't processing your alert at all. All the emails you are getting are from the schedule you set up, which are normal Tableau Subscriptions, which is why none of them have the CSV file in them. In the [install guide](https://github.com/tableau/VizAlerts/blob/master/docs/install_guide.md#custom-subscription-schedules), it says you need to disable the VizAlerts schedules. If you do not do this, VizAlerts won't work. This is a good time to go back and review the install guide for any other steps that you may have missed.

Now, we need to figure out why the test_alert comments are not working. After you disable the VizAlerts schedule, you should see one row in the VizAlertsConfig/ScheduledTriggerViews sheet. Please share a screen cap of that data so I can verify that it's there and reflects your AlumniEmail viz.

**Comment by TNS-reaj** [comment]
<img width="876" alt="09" src="https://user-images.githubusercontent.com/65303850/87725892-1632d380-c78c-11ea-9ce3-7e6ded92013d.PNG">
I have disabled all VizAlerts Schedule.

**Comment by TNS-reaj** [comment]
After I disabled VizAlerts Schedule, I don't receive the email report anymore.

**Comment by mcoles** [comment]
That is expected, and okay. Now what we need to do is troubleshoot your VizAlertsConfig workbook.

1. Would you please edit the connection and confirm that the postgreSQL server you are connecting to is in fact that same server that you are publishing the Alumni Email viz to? Sometimes folks forget which their workbook is pointing to.

![image](https://user-images.githubusercontent.com/14928335/87795836-74e46580-c7fd-11ea-85f2-e48d3d3a1be0.png)

2. If you know you have the right server, then confirm that the user you subscribed to the Alumni Email viz with has a valid email address in Tableau Server. Any account which has a blank email address won't be picked up by VizAlerts.

![image](https://user-images.githubusercontent.com/14928335/87796590-6ba7c880-c7fe-11ea-8634-877b6384d8d0.png)

3. Finally, please confirm that you are still subscribed to Alumni Email on the VizAlerts 15 minute schedule, and that that schedule is disabled in Tableau Server just like is shown here:

![image](https://user-images.githubusercontent.com/14928335/87797654-ddccdd00-c7ff-11ea-9d56-2899d3bf87f7.png)

![image](https://user-images.githubusercontent.com/14928335/87797629-d4dc0b80-c7ff-11ea-9cdc-97be72d627a4.png)


If you have confirmed all of these steps, then my expectation would be that you see one row in the VizAlertsConfig / ScheduledTriggerViews sheet. This will indicate that VizAlerts will now start processing your Alumni Email as expected.

**Comment by TNS-reaj** [comment]
Hi Matt,
I confirmed that all these steps. 
I have a change made today. At step 1, I used to 
<img width="839" alt="10" src="https://user-images.githubusercontent.com/65303850/87827244-8141e000-c848-11ea-971f-a3f9daf255d1.PNG">
log into the PostgreSQL with the server name, I changed it log into the PostgreSQL with the alias name which the tableau web page we are using alias name. So I see the VizAlertsCofig view a different than last time. Is this the line which you were talking about?
When I undisabled the schedule, I received an email but still don't see the csv file.

**Comment by TNS-reaj** [comment]
<img width="839" alt="10" src="https://user-images.githubusercontent.com/65303850/87827550-193fc980-c849-11ea-8bcb-a8fa928ec50f.PNG">
Hi Matt,
I confirmed that all these steps.
I have a change made today. At step 1, I used to log into the PostgreSQL with the server name, I changed it log into the PostgreSQL with the alias name which the tableau web page we are using an alias name. So I see the VizAlertsCofig view a different than last time. Is this the line which you were talking about?
When I undisabled the schedule, I received an email but still don't see the csv file.

**Comment by TNS-reaj** [comment]
and the VizAlerts isn't processing as well.
2020-07-17 16:20:07 - [INFO] - main - Processing a total of 0 alerts

**Comment by mcoles** [comment]
Okay, good to see that we have three subscriptions to work on, now. VizAlerts will, on the first execution, note the subscriptions. On a subsequent run, it will check for the subscriptions schedules next run time having passed, at which point it will actually process the alerts. I am not sure why there are three of them, so that's something to look into...but if at least one is from the workbook that you showed earlier, with the Email Action field and the Email Attachment field in the detail, then you should certainly get an email at some point with a CSV attached. If you are not seeing VizAlerts do anything at all in the logs, then I would double-check the \conf\vizalerts.yaml file to ensure that the **server** is set to the one you expect, as is the **vizalerts.source.site:**.

**Comment by TNS-reaj** [comment]
Hi Matt,
I have gone over all the installation guides and didn't see anything missing or a mistake. The CSV file is still unable to export. I checked the log file there is no error. But when I ran the vizalerts.exe, I do see there is no alerts processing.  2020-07-19 23:16:46 - [INFO] - Processing a total of 0 alerts. Is there any other file I can check it?
Thanks

**Comment by TNS-reaj** [comment]
btw, the vizalerts.source.site: is Default. If I put our domain name that will have the error. Any thought?

**Comment by TNS-reaj** [comment]
vizalerts.source.viz: 'VizAlertsConfig/ScheduledTriggerViews'
vizalerts.source.site: 'Default'

**Comment by TNS-reaj** [comment]
We are using tableau server version 2019.3.1
In yaml file, If I put server.version 2019.3.1 it shows server.version value is invalid -- only version 8,9,10 is allowed.  So I have to change the server.version to 10.
Just want to confirm is that correct?

**Comment by mcoles** [comment]
Correct, that config line is confusing and useless and will be removed in the future. Leave it at 10.

**Comment by TNS-reaj** [comment]
<img width="337" alt="test cert 3 true report at 1_15" src="https://user-images.githubusercontent.com/65303850/88223418-736bd080-cc35-11ea-88ec-bab4efebf3d3.PNG">

I don't see anything wrong in the yaml file. The temp file has generated but is empty. I don't see the error in the log file. As you see the output in here, "Processing a total of 0 alerts. Any idea?

Thanks for your help

**Comment by mcoles** [comment]
I'm sorry Jen--at this point I don't have much more time to invest in helping troubleshoot this. If you're posting a "test_alert" comment and still getting "Processing a total of 0 alerts" then something is fundamentally wrong at a configuration level, either with the VizAlertsConfig workbook (which postgreSQL database you're connecting to) _or_ in the vizalerts.yaml file (either **server** or **vizalerts.source.viz** or **vizalerts.source.site** ). It's going to be an issue with any and all of those, so I guess I would recommend going through each systematically and making sure you are pointing to the same Server resources with each, and not referring to a different one.

**Comment by mcoles** [comment]
It's worth mentioning that while I don't do direct help via conference call, our own Tableau sales consultants can assist with this, as well as [DataBlick](https://www.datablick.com/services).

**Comment by TNS-reaj** [comment]
Hi Matt: I understand. Thank you so much for your help.
