### ISSUE TITLE
Error Opening sample tbw file

### ISSUE THREAD

**Issue by DataManinPeoria** [tableau/VizAlerts#168]
Hi - i'm reading through the how to documentation and when i try to load the sample workbook i receive this error:

Unable to complete action
Errors occurred while trying to load the workbook "C:\Users\christopher.campo\Downloads\VizAlertsConfig.twb". The load was not able to complete successfully.
Error Code: D2E8DA72
This document has no version number.

I am running 2020.3 Desktop if this helps.

Thank you.

**Comment by mcoles** [comment]
This means that you're trying to download the workbook directly from GitHub, and it's saving as an HTML page instead of an XML document. Instead, download the .zip file from the [latest release](https://github.com/tableau/VizAlerts/releases), extract the files, then open it. Should solve your problem.
