### ISSUE TITLE
Locales defaulting to semicolon delimiters cannot use Advanced Alerts

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#17]
In some countries, the standard text delimiter used is ";" rather than ",". This (apparently) results in Tableau Server exporting a CSV using that delimiter rather than a comma, but VizAlerts is still expecting a comma.

We should find a way to adjust the behavior to whatever the appropriate setting is for the locale, and use that.

See https://community.tableau.com/message/475397 for more details.

**Comment by mcoles** [comment]
We had another user encounter this problem:

https://community.tableau.com/thread/221796

May be able to fix via a config setting that injects a delimiter value into 

https://github.com/tableau/VizAlerts/blob/master/vizalert/vizalert.py#L91

e.g. 

```
        self.csv_reader = csv.reader(f, delimiter=';', **kwargs)
```

The CSV module includes a "sniff" method that we might be able to use to auto-configure the CSV settings.

https://docs.python.org/2/library/csv.html

**Comment by mcoles** [comment]
```
        dialect = csv.Sniffer().sniff(f.readline(), delimiters=',;') # try to auto-detect format
        f.seek(0)
        self.csv_reader = csv.reader(f, dialect, **kwargs)
```

**Comment by mcoles** [comment]
Above fix doesn't work if the viz has no data. :( Need to test for a line first...

**Comment by mcoles** [comment]
Didn't go with the sniff method--I just couldn't get it working reliably enough in different situations. Instead, there's now an optional config value in vizalerts.yaml that will let you set the delimiter. So far we've only heard of ',' and ';' that need to be supported, so this should work for most cases.

**Comment by MrPozor** [comment]
I have a problem with this config value. For some reason my yaml file defaulted to `data.coldelimiter:  ';'`. Maybe because the server is set up in French.
I changed this to `data.coldelimiter: ','` but VizAlerts stops working. The error message I get is:

`Could not process source viz data from VizAlertsConfig/ScheduledTriggerViews for the following reason:

Invalid regular expression found. Could not evaluate expression '' in the field allowed_from_address. Raw error:

allowed_from_address
` 

I checked the ScheduledTriggerViews, the allowed_from_address and the default_allowed_from_address fields and they don't contain anything out of the ordinary. Nothing with colons or semicolons anyway. What could trigger this error?

**Comment by mcoles** [comment]
Hmmm...the yaml file should not default to ";" for that value--the default is always ","

https://github.com/tableau/VizAlerts/blob/master/config/vizalerts.yaml#L56

If your server is set up in French, then check the "Correct Answer" in this thread: https://community.tableau.com/message/475397

You can change your regional settings for the delimiter value. That way you should be able to have "," if you want. Give that a shot and see if it works.

**Comment by MrPozor** [comment]
OK, I now understand the error better. It has nothing to do with the "From" address. The error is caused by the ScheduledTriggerViews.csv still using ";" while VizAlerts expects "," when changing the `data.coldelimiter`.
Put differently, I cannot just set `data.coldelimiter: ','` for CSV data to be mailed correcty with a comma without also making sure that Tableau is exporting the ScheduledTriggerViews.csv with a comma as well.

This means this is more a Tableau issue then a VizAlerts issue.
