### ISSUE TITLE
Whenever Server or webserver(Reverse proxy server) restarts, we see Error generating trusted ticket

### ISSUE THREAD

**Issue by sushanthmr** [tableau/VizAlerts#178]
On weekend Whenever Server or webserver(Reverse proxy server) restarts, we get this message trusted_ticket_test - UserWarning generating trusted ticket: Error generating trusted ticket. Value of ticket is -1.

After a day or two it gets resolved if not I need to run vizalerts from another server to fix this issue. 

Also is it possible to stop rerunning all vizalerts when we start a new process?

Thanks,
Sushanth

**Comment by mcoles** [comment]
While digging through the [VizQLServer logs ](https://help.tableau.com/current/server/en-us/trusted_auth_trouble_1return.htm)is the only way to know for sure what the root cause of the "-1" error code is, my guess is that your server is not configured for a static IP address, so that when you restart it, requests are coming from a new address that has not been trusted in your config.

For your second question, if you're referring to preventing VizAlerts from running alerts it missed during an outage window when you start it back up again, yes, you can prevent that by deleting the vizalerts.state file in the ops folder before you turn it back on. That file contains the next time each alert is supposed to run, and when VizAlerts sees that that time occurs in the past, it runs the alert. If you delete it, you're effectively allowing VizAlerts to start with a blank slate so that it does not "remember" that it needs to run the missed alerts.

**Comment by sushanthmr** [comment]
Thanks Matt for your valuable inputs.

**Comment by sushanthmr** [comment]
@mcoles We are using static IP addresses. We have two reverse proxy apache servers (X and Y) on top of tableau servers. 
Whenever it is restarted we are seeing this issue. 

Say there is two way communication between X reverse proxy server and tableau server and if we restart X revers proxy server. There are chances that tableau server will try to establish communication with Y reverse proxy server in that case Vizalert will fail with Value of ticket is -1.
