### ISSUE TITLE
Test alerts break in 2021.1

### ISSUE THREAD

**Issue by sowbhariowg** [tableau/VizAlerts#180]
Recently we upgraded Tableau from 2020.3 to 2021.1 & were having issues with the test alerts. The VizAlerts version in our environment is 2.1.1 & referring to the link [https://github.com/tableau/VizAlerts/issues/175](url) we did make the change to the config workbook & still facing the issue. Does anyone else facing the same issue or have a workaround.

**Comment by mcoles** [comment]
I had the same issue, recently, but then realized it was because I was adding "test_alert" comments to a viz on our Online site, not our Tableau Server. 😛 

So in your case, the test_alert comments are not triggering an alert as they should, correct? Here are some things to run down before we dive deep into logs and such:

1. Add a test_alert comment, then download the CSV summary data from your config workbook. The field "is_test" should show as TRUE for the viz in question. If not, double-check that you added your comment to the right Tableau Server instance, that the Config workbook is pointing to the correct PostgreSQL repository, and that the workbook you're looking at isn't some copy or other. If it still shows as FALSE for the viz you added the comment to, then consider downloading a fresh version of [the workbook](https://raw.githubusercontent.com/tableau/VizAlerts/master/config/VizAlertsConfig.twb) from GitHub, and see if it shows then. Note that if it takes longer than five minutes to check the workbook after you enter the comment, it won't show, so you'll have to add a new comment.

2. If the record shows up, but VizAlerts is still not processing it, then check to ensure that it's running. Ensure the vizalerts.yaml file still refers to the correct server, and the correct values are stated for the **vizalerts.source.viz** and **vizalerts.source.site** keys.

3. If the test_alert record is showing up in the config workbook, and you've checked all the other stuff, then add it again, kick off a single run of VizAlerts right after, then grab the relevant log lines and share them here (redact as necessary for security and privacy). I'll take a look at them and see if I can figure out what's up.
