### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by jmiller-ipm** [tableau/VizAlerts#181]
I'm migrating Tableau Servers, upgrading to 2020.4 and updating to latest release of VizAlerts at the same time. When I get to testing the executable, Postdata is showing b&#x27;username={username goes here}&#x27; and I believe that's affecting the url parsing. In previous releases, Postdata lists just username={username goes here}.

![image](https://user-images.githubusercontent.com/66689367/123317278-af14b780-d4e2-11eb-84f8-e5d8ef9f4401.png)

**Comment by jdrummey** [comment]
Hi, were you able to get this fixed?

**Comment by jmiller-ipm** [comment]
No sir, just tried again and same result. I've attempted to play around with the YAML encoding as well as slight edits to the python scripts to attempt to handle the string differently. No luck.

I also found this, after I attempted to point the yaml to a pw.txt file:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
![image](https://user-images.githubusercontent.com/66689367/135128265-21210208-69cb-4e5f-9681-a01b7ea3205c.png)

**Comment by mcoles** [comment]
Not sure if you're still struggling with this, but the -1 response means you need to dig into the VizQLServer logs to determine the root cause of the issue. This is likely a config issue where your new Tableau Server does not trust the host VizAlerts is running from. You can confirm the issue by reviewing the help page whose url is listed in the error message. Could be an issue with VizAlerts, but I have not heard of anyone struggling with issues due to the POST data we're sending in the new version.
