### ISSUE TITLE
Installation help required

### ISSUE THREAD

**Issue by peterkalman** [tableau/VizAlerts#187]
Hey everyone, 
In the installation guide there is a point where you need to allow vizalerts to use trusted authentication.
Where you need to use this line of code.
For versions 10.5 and higher:
    tsm configuration set -k wgserver.trusted_hosts -v <HOSTNAME OF VIZALERTS HOST>
    
However no where does it mention what is the {VizAlerts Host}. Is it the domain of my server or is it where I store vizalerts?
The guide is very vague in that regard , I read it top to bottom and did everything else and it still doesn't work properly.
I figured that might be because I don't know what to write in the  {VizAlerts Host}

Any help would be appreciated.

**Comment by mcoles** [comment]
With this command, you are telling Tableau Server to implicitly trust any request it receives from {VizAlerts Host} for a trusted ticket, which grants the ability to render a view under the username the ticket was created under. The host is wherever you have installed VizAlerts, since that is the application you'll be issuing ticket requests from.
