### ISSUE TITLE
Config file fails to load

### ISSUE THREAD

**Issue by mcoles** [tableau/VizAlerts#193]
pyyaml deprecated the .load(f) call. You must now provide a Loader along with the file you wish to load. Should simply [update it](https://github.com/tableau/VizAlerts/blob/master/tabUtil/__init__.py#L34) from:

`yaml_opts = yaml.load(f)`

to

`yaml_opts = yaml.load(f, Loader=yaml.SafeLoader)`

**Comment by cyberoner1** [comment]
getting error:
tabUtil\__init__.py:34: YAMLLoadWarning: calling yaml.load() without Loader=...
is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.o
rg/load for full details.
 yaml_opts = yaml.load(f, Loader=yaml.SafeLoader)
Could not initialize configuration file due to an unknown error: 13

**Comment by mcoles** [comment]
You changed [line 34](https://github.com/tableau/VizAlerts/blob/master/tabUtil/__init__.py#L34) to use `yaml_opts = yaml.load(f, Loader=yaml.SafeLoader)`, and it's still throwing that error? That should not be...

**Comment by mcoles** [comment]
See #195
