### ISSUE TITLE
Setting a customized mail header and body

### ISSUE THREAD

**Issue by amirne1** [tableau/VizAlerts#202]
Hi all,
We are going to use VizAlerts in embedded Tableau for our external customers.
Does anyone familiar with a way to customize the mail header and body by adding my own text template?
Thanks in advance.
Amir.

**Comment by mcoles** [comment]
I'm not familiar with how you might use VizAlerts in an embedded scenario--would it be possible to explain that use case in more detail? It sounds interesting.

As the alert creator, you can easily customize the header and footer using the Email Header and Email Footer fields, and format the content using HTML strings. However, you cannot _enforce_ them if you are giving your users the ability to edit those fields, because then they can change them to whatever they want. That's why I think it will be helpful to better understand what you are trying to do with the embedded situation. If you are exposing a web form that only lets them fill in specific parts of the email content, then it may be as simple as setting the header and footer field calcs the way you want, but only exposing the Email Body field to the end users.
