### ISSUE TITLE
Split actions from a single alert across multiple threads for improved throughput

### ISSUE THREAD

**Issue by jdrummey** [tableau/VizAlerts#76]
This is an issue we ran into while preparing the swag demo for the VizAlerts session at the 2016 Tableau Conference https://community.tableau.com/docs/DOC-10039. A single alert could have hundreds of actions (outgoing emails, text messages, etc.) and since the alert runs in a single thread it would take that alert as long to process as all of the actions in the alert. In the case of the swag demo since it took ~1 second per text message that meant that the theoretical 100s of text messages (211 in the actual demo) could take several minutes to process and we wanted them to go out much faster than that.

The workaround for the swag demo was to create four different trigger views that could be spread across four threads for faster processing, that took some fancy footwork with table calculation filters. 

A next generation implementation of threading could automatically handle this scenario. I'm thinking this could be implemented in two parts: 1) using a queue for each alert for downloading the content references, and 2) using another queue for each alert for the actions.

There is the question of prioritization, given M alerts with N actions, how should VizAlerts prioritize? Should it process all actions from alert M.1 first or simultaneously tackle M.1, M.2, ... M.x alerts and then as threads become available tackle downloading content references and actions for other alerts?

**Comment by mcoles** [comment]
Ben Schossow from Slalom caught me later on during the conference and mentioned that he was trying to build a really big alert as well, and had assumed multi-threading would cover his scenario. So this need is definitely there.

IIRC, there is a "priority" calc built into the config workbook. It currently uses the priority of the Schedule as a default, but can be edited if customizations are needed. So that would be the overall priority order that each Alert is processed.

Within that, I think there should be generic field used to prioritize the overall alert actions. Maybe call it "Priority Order" or somesuch. For each row in the alert, if consolidation were in play, we'd run the de-duplication routine, and then form the consolidation blocks. Then the blocks would need to be processed in order of their minimum priority level within the block. For example, if there were six rows of data, with three total emails being sent due to consolidation, they'd be processed according to the order of whichever block had a row with the lowest overall priority.

I guess we could put in tiebreaker logic, where in the case of a tie, the second-lowest value would break the tie...but that might just be a lot work for pretty rare use case.

**Comment by mcoles** [comment]
For multi-threading each alert, I think that should be another config viz calc, with a new default value in the parameter. That allows for flexible thread configuration for each alert. The admin can then balance the number of threads they want run, according to the scheduling, how important each alert is, and how much they want to hit their Server.

It may make sense to have some kind of separate config for Email Actions vs SMS Actions VS Whatever other actions we create, and a separate one for Content Refs, since they hit Tableau Server. But that could get complicated, I think. An overall number of threads per alert would be simpler to configure. Now that I think about it, though, they'd probably have to complete all the content refs before the Actions could actually be taken. So we'd start the alert, download the trigger data, spin up the content ref worker threads, finish processing content refs, then spin up the same number of Action threads, sending emails, copying files, SMS's whatevers.

If we tackle this, I'd like to see the content references get class-ified, as was done with the Action Fields. It will make the multi-threading code easier, and we'll be in a better place to improve error handling at the same time (failing to process a single content ref shouldn't cause the whole alert to break). Plus we'll have more structured info on what VizAlerts actually did, which lets us do stuff like structure logs or output to an RDBMS more easily.

**Comment by mcoles** [comment]
Have an early version of this that works now. Initially, we'll restrict multithreading to ready-to-go SMS and Email sends. Content refs will still be processed serially for the time being. Eventually most, if not all steps to process a given VizAlert will make use of the new Task class. Some tasks like field validation can't really be multithreaded, so they'll run first, then the latter tasks will be created and enqueued, then processed in some priority order.

Efficiency gains seem good so far! Running the Advanced Alert Test, I get the following results to send all 32 emails (just to PaperCut, not a real SMTP server):

1 thread: 34s
2 threads: 17s
10 threads: 6s

There may be some concerns with anti-hammering defenses on the server that whoever is configuring VizAlerts might need to work with IT on. But from our end, it will be flexibly configurable.

**Comment by jdrummey** [comment]
Love the speed increase!

**Comment by mcoles** [comment]
This will be in 2.1.0
