### ISSUE TITLE
Vizalert config changes

### ISSUE THREAD

**Issue by rishabh1991** [tableau/VizAlerts#80]
Hi 

What necessary changes do I have to make in vizalert to send notification to my gmail id?

Thanks 
Rishabh

**Comment by mcoles** [comment]
Hi Rishabh. For future reference, the place to ask questions and get assistance with VizAlerts is https://community.tableau.com/vizalerts . But I'll do my best to answer your question here, this time.

If you are using VizAlerts 1.x, then you need to add gmail.com to the list of allowed domains in config\vizalerts.yaml. Note that this will allow ANY alert author to send email to any gmail.com address--not just your own alerts.

If you are using VizAlerts 2.x, you need to ensure that the allowed_recipient_addresses field has a regular expression in it that your gmail.com address will match. You can edit the parameter used for the default value if you want it to apply to all alerts, or you can edit the calculated field and make this conditional, so that it only applies to your own alerts, and does not allow _everyone_ to send mail to gmail.com addresses. See examples in the calculation, the field comments in the viz, and in the user guide.

Note that both of these tasks require you to be the administrator of VizAlerts.
